version: '3'

services:
  pgsql:
    image: mariadb
    container_name: db-apps
    volumes:
      - ./data-mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      - jon-network

  php:
    build: ./dockerfiles
    container_name: php-apps
    volumes:
      - "./src:/var/www/src"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - pgsql
    networks:
      - jon-network

  nginx:
    image: nginx:latest
    container_name: web-apps
    depends_on:
      - php
    volumes:
      - "./src:/var/www/src"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8081:80"
    restart: always
    networks:
      - jon-network

networks:
  jon-network:
    external: true
